import Header from "@/components/common/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import Providers from "@/context/Providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShadAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/@highlightjs/cdn-assets@11.9.0/styles/nord.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider>
            <main className="grid grid-rows-[auto_1fr] no-bar w-full  bg-[#070606] text-[#F0F0F0] ">
              <Header />
              <div className="px-4 lg:px-[20svw] no-bar mx-auto">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
